flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/CindyLinz/hs-tls
    commit: ce841378fba81fca12d604851f27caa26d081d79
  subdirs:
  - core
  extra-dep: true
extra-deps:
- HFuse-0.2.4.5
- google-drive-0.4.1
- google-oauth2-0.2.2
- unix-bytestring-0.3.7.3
resolver: lts-7.9
